server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SmartStudy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  rabbitmq:
    host: localhost
    username: Michelle
    password: 1234
    port: 5672
    virtual-host: vhost01 #虚拟主机
    courseExcName: courseTopicExchange #课程Topic-直连交换机（direct）

  mail:
    host: smtp.126.com
    username: studyserver1052@126.com
    password: AFJSTAOXWYIIEHVA # 授权码 QGSHTKHEWNTQVBFA
    from: studyserver1052@126.com # 发送者

jwt:
  secret-key-str: VGhpcyBpcyBTQSBHcm91cCAxMi5IYXZlIHRvIGJ1aWxkIGEga2V5IGxvbmcgZW5vdWdoIGZvciB0aGUgYWxnb3JpdGhtIHRvIHJ1bg==
  # token 有效期 单位：天
  ttl: 99


mybatis:
  mapper-locations: classpath:mapper/*.xml

# 开启 MyBatis Plus SQL 打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus.core: debug
